# Generated by Django 5.0.1 on 2025-06-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViolenciaFamiliar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_doc_denuncia', models.IntegerField()),
                ('libro', models.CharField(max_length=200)),
                ('num_denuncia', models.CharField(max_length=200)),
                ('tipodenuncia', models.CharField(max_length=200)),
                ('situaciondenuncia', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('subtipo', models.CharField(max_length=300)),
                ('modalidad', models.CharField(max_length=200)),
                ('fec_hecho_fecha', models.DateField(blank=True, null=True)),
                ('fec_hecho_hora', models.TimeField(blank=True, null=True)),
                ('dpto', models.CharField(max_length=200)),
                ('prov', models.CharField(max_length=200)),
                ('distrito', models.CharField(max_length=200)),
                ('tipovia', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('cuadra', models.CharField(blank=True, max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('situacionpersona', models.CharField(max_length=200)),
                ('fec_nacimiento_fecha', models.DateField(blank=True, null=True)),
                ('fec_nacimiento_hora', models.TimeField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(max_length=50)),
                ('estadocivil', models.CharField(max_length=100)),
                ('gradoinstruccion', models.CharField(blank=True, max_length=200)),
                ('ocupacion', models.CharField(blank=True, max_length=200)),
                ('pais_natal', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('descripcioncomisaria', models.CharField(max_length=300)),
                ('fec_registro_fecha', models.DateField(blank=True, null=True)),
                ('fec_registro_hora', models.TimeField(blank=True, null=True)),
                ('xx', models.FloatField()),
                ('yy', models.FloatField()),
            ],
            options={
                'db_table': 'incidencias_violenciafamiliar',
                'managed': True,
            },
        ),
    ]
