# Generated by Django 5.0.1 on 2025-07-01 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó la carga')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la carga', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='violenciafamiliar',
            name='carga',
            field=models.ForeignKey(blank=True, help_text='Lote de importación al que pertenece esta incidencia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='incidents.registrocarga'),
        ),
    ]
